<a href="https://colab.research.google.com/github/thinnarat007/python_dataviz2024/blob/main/midterm_exam_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
from scipy import stats

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [4]:
import os

path = '/content/drive/MyDrive/Data_viz2024_Data/Test'

test_TidyData = os.path.join(path,'test-TidyData_2024.xlsx')
print(test_TidyData )

/content/drive/MyDrive/Data_viz2024_Data/Test/test-TidyData_2024.xlsx

In [5]:
test_TidyData = pd.read_excel(test_TidyData)
test_TidyData

,month,station,rep.,Chlo_a,Chlo_b,total_Caro,Temp.,pH,EC,Salinity,TDS,DO,Nitrate,Ammonium,Phosphate,No.Algal_cell,@dropdown
0,July_2018,1,1,0.094645,0.011954,0.026780,30.2,5.54,622.7,330.3,545.2,4.37,0.172902,0.052817,0.012748,1.635833e+05,NaN
1,July_2018,2,1,0.038433,0.059019,0.021387,29.1,6.24,580.7,307.0,488.2,6.55,0.154197,0.144843,0.006086,1.166667e+06,NaN
2,July_2018,3,1,0.043884,0.089415,0.023223,29.7,5.52,547.1,289.4,462.2,5.67,0.153097,0.154321,0.014158,2.970000e+06,NaN
3,July_2018,4,1,0.039836,0.064552,0.016537,29.2,5.92,473.6,249.2,397.9,0.69,0.157026,0.387408,0.056951,5.066667e+05,NaN
4,July_2018,5,1,0.044712,0.062424,0.022990,29.5,5.79,685.5,366.0,581.2,4.46,0.204024,0.043387,0.007239,1.265000e+06,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193,July_2019,2,3,0.030521,0.015358,0.018067,31.2,7.74,580.5,309.2,517.0,6.31,0.132034,0.030959,-0.000064,2.665833e+05,NaN
194,July_2019,3,3,0.024081,0.020217,0.015981,29.7,7.50,513.0,272.6,436.0,3.00,0.230116,0.059103,-0.000064,6.428333e+05,NaN
195,July_2019,4,3,0.015525,0.009612,0.009373,31.5,7.51,550.9,289.8,498.4,4.02,0.123546,0.136428,-0.000064,2.945000e+05,NaN
196,July_2019,5,3,0.015180,0.011811,0.009697,28.5,7.31,540.6,287.4,443.4,1.53,0.110028,0.056057,-0.000064,3.470833e+05,NaN
197,July_2019,6,3,0.008556,0.010605,0.005704,31.5,7.71,544.7,288.2,493.8,6.32,0.165042,0.105817,-0.000064,3.692500e+05,NaN

In [6]:
test_TidyData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 198 entries, 0 to 197
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   month          198 non-null    object
 1   station        198 non-null    int64
 2   rep.           198 non-null    int64
 3   Chlo_a         198 non-null    float64
 4   Chlo_b         198 non-null    float64
 5   total_Caro     198 non-null    float64
 6   Temp.          198 non-null    float64
 7   pH             198 non-null    float64
 8   EC             198 non-null    float64
 9   Salinity       198 non-null    float64
 10  TDS            198 non-null    float64
 11  DO             198 non-null    float64
 12  Nitrate        198 non-null    float64
 13  Ammonium       198 non-null    float64
 14  Phosphate      198 non-null    float64
 15  No.Algal_cell  198 non-null    float64
 16  @dropdown      0 non-null      float64
dtypes: float64(14), int64(2), object(1)
memory usage: 26.4+ KB

In [ ]:
test_TidyData.shape

(198, 17)

In [9]:
# แยกปีออกจากคอลัมน์ month
test_TidyData['year'] = test_TidyData['month'].str.split('_').str[1]
test_TidyData

,month,station,rep.,Chlo_a,Chlo_b,total_Caro,Temp.,pH,EC,Salinity,TDS,DO,Nitrate,Ammonium,Phosphate,No.Algal_cell,@dropdown,year
0,July_2018,1,1,0.094645,0.011954,0.026780,30.2,5.54,622.7,330.3,545.2,4.37,0.172902,0.052817,0.012748,1.635833e+05,NaN,2018
1,July_2018,2,1,0.038433,0.059019,0.021387,29.1,6.24,580.7,307.0,488.2,6.55,0.154197,0.144843,0.006086,1.166667e+06,NaN,2018
2,July_2018,3,1,0.043884,0.089415,0.023223,29.7,5.52,547.1,289.4,462.2,5.67,0.153097,0.154321,0.014158,2.970000e+06,NaN,2018
3,July_2018,4,1,0.039836,0.064552,0.016537,29.2,5.92,473.6,249.2,397.9,0.69,0.157026,0.387408,0.056951,5.066667e+05,NaN,2018
4,July_2018,5,1,0.044712,0.062424,0.022990,29.5,5.79,685.5,366.0,581.2,4.46,0.204024,0.043387,0.007239,1.265000e+06,NaN,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193,July_2019,2,3,0.030521,0.015358,0.018067,31.2,7.74,580.5,309.2,517.0,6.31,0.132034,0.030959,-0.000064,2.665833e+05,NaN,2019
194,July_2019,3,3,0.024081,0.020217,0.015981,29.7,7.50,513.0,272.6,436.0,3.00,0.230116,0.059103,-0.000064,6.428333e+05,NaN,2019
195,July_2019,4,3,0.015525,0.009612,0.009373,31.5,7.51,550.9,289.8,498.4,4.02,0.123546,0.136428,-0.000064,2.945000e+05,NaN,2019
196,July_2019,5,3,0.015180,0.011811,0.009697,28.5,7.31,540.6,287.4,443.4,1.53,0.110028,0.056057,-0.000064,3.470833e+05,NaN,2019
197,July_2019,6,3,0.008556,0.010605,0.005704,31.5,7.71,544.7,288.2,493.8,6.32,0.165042,0.105817,-0.000064,3.692500e+05,NaN,2019

In [13]:
# สร้าง DataFrame สำหรับปี 2018 และ 2019
data_2018 = test_TidyData[test_TidyData['year'] == '2018']
data_2019 = test_TidyData[test_TidyData['year'] == '2019']

In [19]:
# คำนวณค่าเฉลี่ยของ Chlo_a สำหรับแต่ละ station ในปี 2018 และ 2019
mean_2018 = data_2018.groupby('station')['Chlo_a'].mean()
mean_2019 = data_2019.groupby('station')['Chlo_a'].mean()

In [23]:
# หาความแตกต่างของค่าเฉลี่ย
difference = mean_2019 - mean_2018

# แสดงผลลัพธ์
print(difference)

station
1   -0.034261
2   -0.020201
3   -0.030228
4   -0.025173
5   -0.023331
6   -0.028215
Name: Chlo_a, dtype: float64

In [27]:
# สร้างตาราง Pivot Table เพื่อคำนวณค่าเฉลี่ย Chlo_b สำหรับแต่ละ station และเดือน
chlo_b_mean_table = pd.pivot_table(test_TidyData, values='Chlo_b', index='station', columns='month', aggfunc='mean')

# แสดงผลลัพธ์
print(chlo_b_mean_table)

month    Apr_2019  Aug_2018  Dec_2018  Jan_2019  July_2018  July_2019  \
station
1        0.051381  0.075665  0.070061  0.022451   0.046688   0.014365
2        0.019378  0.065403  0.064375  0.014968   0.062731   0.013691
3        0.030775  0.065179  0.080867  0.017722   0.073561   0.017439
4        0.020170  0.061289  0.061951  0.012142   0.061395   0.009257
5        0.027015  0.060107  0.070085  0.009789   0.064623   0.011054
6        0.025655  0.063027  0.065663  0.013856   0.056193   0.010073

month    June_2019  May_2019  Nov_2018  Oct_2018  Sep_2018
station
1         0.020548  0.015949  0.075937  0.131764  0.063890
2         0.013194  0.028765  0.064552  0.122767  0.074578
3         0.013301  0.015890  0.097963  0.106404  0.076292
4         0.013821  0.015559  0.070605  0.090834  0.064670
5         0.013880  0.016623  0.063866  0.082381  0.060733
6         0.008583  0.023882  0.073360  0.079449  0.061750